import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import React, { useState } from 'react';

import Link from 'next/link';

import Header from '@/components/Header';
import Footer from '@/components/Footer';

import {
    Heading,
    Box,

    Tabs,
    TabList,
    Tab,
} from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    return (
        <>
            <Head>
                <title>Skip.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${styles.main} ${inter.className}`}>
                {/* ヘッダ */}
                <Header defaultIndex={3}/>

                {/* コンテンツ */}
                <div className={styles.content}>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                </div>

                {/* フッター */}
                <Footer />
            </main>
        </>
    )
}