import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import React, { useState } from 'react';

import Link from 'next/link';


import {
    Heading,
    Box,

    Tabs,
    TabList,
    Tab,
} from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    return (
        <>
            <Head>
                <title>Skip.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>

                {/* ヘッダ */}
                <div className={styles.header}>
                    <Box bg="gray.800" color="white" p={4} id="head">

                        {/* サイト名 */}
                        <div className={styles.siteName}>
                            <Heading size="lg" colorScheme="whiteAlpha">
                                <Link href="../">
                                    三毛猫のアンドロン
                                </Link>
                            </Heading>
                        </div>


                        {/* グローバルナビ */}
                        <div className={styles.navi}>
                            <Tabs variant="soft-rounded" colorScheme="green" defaultIndex={2}>
                                <TabList>
                                    <Tab>
                                        <Link href="/">
                                            Top
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/profile">
                                            Profile
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/works">
                                            Works
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/blog">
                                            Blog
                                        </Link>
                                    </Tab>
                                </TabList>
                            </Tabs>


                        </div>

                        {/* ハンバーガーメニュー */}
                    </Box>
                </div>

                {/* コンテンツ */}
                <div className={styles.content}>
                    <div>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗1
                        </Box>
                        <Box bg="gray.400" color="white" className={styles.workBlock}>
                            進捗2
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗3
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗4
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗5
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗6
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗7
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗8
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗9
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗10
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗11
                        </Box>
                        <Box bg="gray.500" color="white" className={styles.workBlock}>
                            進捗12
                        </Box>
                    </div>
                </div>

                {/* フッター */}
                <div className={`${styles.footer} ${styles.clear_box}`}>
                    <Box bg="gray.800" color="white" p={4}>
                        
                        &copy;skip
                    </Box>
                </div>



            </main>

        </>
    )
}
