import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import React, { useState } from 'react';

import Link from 'next/link';


import {
    Heading,
    Box,

    Tabs,
    TabList,
    Tab,
} from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

    return (
        <>
            <Head>
                <title>Skip.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>

                {/* ヘッダ */}
                <div className={styles.header}>
                    <Box bg="gray.800" color="white" p={4} id="head">

                        {/* サイト名 */}
                        <div className={styles.siteName}>
                            <Heading size="lg" colorScheme="whiteAlpha">
                                <Link href="../">
                                    三毛猫のアンドロン
                                </Link>
                            </Heading>
                        </div>


                        {/* グローバルナビ */}
                        <div className={styles.navi}>
                            <Tabs variant="soft-rounded" colorScheme="green" defaultIndex={1}>
                                <TabList>
                                    <Tab>
                                        <Link href="/">
                                            Top
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/profile">
                                            Profile
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/works">
                                            Works
                                        </Link>
                                    </Tab>
                                    <Tab>
                                        <Link href="/blog">
                                            Blog
                                        </Link>
                                    </Tab>
                                </TabList>
                            </Tabs>


                        </div>

                        {/* ハンバーガーメニュー */}
                    </Box>
                </div>

                {/* コンテンツ */}
                <div className={styles.content}>
                    <Box bg="gray.500" color="white">
                        アイコンと名前とかをいい感じに書く
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        使える言語とかスキルをいい感じに書く
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        経歴をばーって書く
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.500" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                    <Box bg="gray.400" color="white">
                        aaaaaaaaaaa
                        <br /><br /><br /><br /><br /><br />
                    </Box>
                </div>
                {/* フッター */}
                <div className={styles.footer}>
                    <Box bg="gray.800" color="white" p={4}>
                        &copy;skip
                    </Box>
                </div>



            </main>

        </>
    )
}
