import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Inter } from "next/font/google"
const inter = Inter({ subsets: ["latin"] })

import {
    Box,
    VStack,
    Heading,
} from '@chakra-ui/react'

import Theme from "@/components/Theme"
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Home() {

    return (
        <>
            <Head>
                <title>Skip.com</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${styles.main} ${inter.className}`}>
                {/* ヘッダ */}
                <Header defaultIndex={3} />

                {/* コンテンツ */}
                <Box className={styles.content}>
                    <Box h="800px" bg={Theme.color.backgroundA}>
                        <VStack h="100%" justify="center" spacing={0} >
                            <Heading size="4xl">開発中</Heading>
                        </VStack>
                    </Box>
                </Box>

                {/* フッター */}
                <Footer />
            </main>
        </>
    )
}